# Generated by Django 5.0.3 on 2024-03-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(default=1, upload_to='lost_item_images/'),
            preserve_default=False,
        ),
    ]
