# Generated by Django 5.0.3 on 2024-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0004_alter_lostitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='owner',
            field=models.CharField(max_length=150),
        ),
    ]
