# Generated by Django 5.0.3 on 2024-04-01 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0006_lostitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_contact', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='lostitems.lostitem')),
            ],
        ),
    ]
