# Generated by Django 5.0.3 on 2024-04-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0007_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
